---
- hosts: all
  tasks:
    - name: run echo command
      command: /bin/echo hello k!

    - name: Creates directory
      file:
        path: /home/abhi/ans
        state: directory

    - name: Deletes directory
      file:
        path: /home/abhi/ans
        state: absent
